services:
  app-dev:
    build: .
    container_name: fastapi_app_dev
    profiles: ["dev"]
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MODE=${MODE}

  app-prod:
    build: .
    container_name: fastapi_app_prod
    profiles: ["prod"]
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MODE=${MODE}